# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app_bundle.default_controller:
        class: AppBundle\Controller\HomeController
        arguments:
            - '@templating'
            - "@security.token_storage"
            - "@profile_bundle.user_profile.manipulator"
            - "@doctrine.orm.entity_manager"