parameters:
    profile_bundle.user_profile.manipulator.classname: MMC\Profile\Component\Manipulator\UserProfileManipulator

    profile_bundle.user_profile.securizing_manipulator.classname: MMC\Profile\Component\Manipulator\SecurizingUserProfileManipulator

    profile_bundle.profile_type.validator.classname: MMC\Profile\Component\Validator\ProfileTypeValidator

    profile_bundle.profile_type.provider.classname: MMC\Profile\Component\Provider\ProfileTypeProvider

    profile_bundle.profile.manager.classname: MMC\Profile\Component\Manager\ProfileManager

    profile_bundle.user.manager.classname: MMC\Profile\Component\Manager\UserManager

    profile_bundle.user_profile.manager.classname: MMC\Profile\Component\Manager\UserProfileManager

    profile_bundle.ramsey_uuid_generator.classname: MMC\Profile\Component\UuidGenerator\RamseyUuidGenerator

    profile_bundle.profile_type.create.classname: MMC\Profile\Bundle\ProfileBundle\Form\ProfileType

    profile_bundle.handler_profile_create.classname: MMC\Profile\Component\Handler\Profile\CreateHandler

    profile_bundle.user_provider.classname: MMC\Profile\Component\Provider\UserProvider

    profile_bundle.profile_provider.classname: MMC\Profile\Component\Provider\ProfileProvider

    profile_bundle.userProfile_provider.classname: MMC\Profile\Component\Provider\UserProfileProvider

    profile_bundle.user_browser.classname: MMC\Profile\Component\Browser\UserBrowser

    profile_bundle.securizing_user_browser.classname: MMC\Profile\Component\Browser\SecurizingUserBrowser

    profile_bundle.user_profile_browser.classname: MMC\Profile\Component\Browser\UserProfileBrowser

    profile_bundle.securizing_user_profile_browser.classname: MMC\Profile\Component\Browser\SecurizingUserProfileBrowser

    profile_bundle.user_profile_viewer.classname: MMC\Profile\Component\Viewer\UserProfileViewer

    profile_bundle.securizing_user_profile_viewer.classname: MMC\Profile\Component\Viewer\SecurizingUserProfileViewer

    profile_bundle.profile_param_converter.classname: MMC\Profile\Component\ParamConverter\ProfileParamConverter

    profile_bundle.user_param_converter.classname: MMC\Profile\Component\ParamConverter\UserParamConverter

    profile_bundle.user_profile_param_converter.classname: MMC\Profile\Component\ParamConverter\UserProfileParamConverter

# CONTROLLERS

    profile_bundle.profile_create_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileCreateController

    profile_bundle.profile_show_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileShowController

    profile_bundle.profile_dissociate_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileDissociateController

    profile_bundle.profile_set_priority_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileSetPriorityController

    profile_bundle.profile_activate_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileActivateController

    profile_bundle.profile_associate_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileAssociateController

    profile_bundle.profile_set_rights_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileSetRightsController

    profile_bundle.default_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\DefaultController

    profile_bundle.api_user_browser_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\API\UserBrowserController

    profile_bundle.api_user_profile_browser_controller.classname: MMC\Profile\Bundle\ProfileBundle\Controller\API\UserProfileBrowserController

# VOTERS

    profile_bundle.security.voter.user_profile.classname: MMC\Profile\Component\Security\Voter\UserProfileVoter

    profile_bundle.security.voter.profile.classname: MMC\Profile\Component\Security\Voter\ProfileVoter

    profile_bundle.security.voter.user.classname: MMC\Profile\Component\Security\Voter\UserVoter

services:
    profile_bundle.user_profile.manipulator:
        class: '%profile_bundle.user_profile.manipulator.classname%'
        arguments:
            - '%mmc_profile.profile_class%'
            - '%mmc_profile.userProfile_class%'

    profile_bundle.user_profile.securizing_manipulator:
        class: '%profile_bundle.user_profile.securizing_manipulator.classname%'
        arguments:
            - '@profile_bundle.user_profile.manipulator'
            - '@security.authorization_checker'

    profile_bundle.profile_type.validator:
        class: '%profile_bundle.profile_type.validator.classname%'
        arguments:
            - '@profile_bundle.profile_type.provider'

    profile_bundle.profile_type.provider:
        class: '%profile_bundle.profile_type.provider.classname%'


    profile_bundle.profile.manager:
        class: '%profile_bundle.profile.manager.classname%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@profile_bundle.ramsey_uuid_generator'

    profile_bundle.user.manager:
        class: '%profile_bundle.user.manager.classname%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%mmc_profile.user_class%'

    profile_bundle.user_profile.manager:
        class: '%profile_bundle.user_profile.manager.classname%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@profile_bundle.user.manager'
            - '@profile_bundle.profile.manager'

    profile_bundle.ramsey_uuid_generator:
        class: '%profile_bundle.ramsey_uuid_generator.classname%'

    profile_bundle.profile_type.create:
        class: '%profile_bundle.profile_type.create.classname%'
        arguments: ['@profile_bundle.profile_type.provider']
        tags:
            - { name: form.type }

    profile_bundle.handler_profile_create:
        class: '%profile_bundle.handler_profile_create.classname%'
        arguments:
            - '@profile_bundle.profile_type.validator'
            - '@profile_bundle.user_profile.securizing_manipulator'
            - '@profile_bundle.user_profile.manager'

    profile_bundle.user_provider:
        class: '%profile_bundle.user_provider.classname%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%mmc_profile.user_class%'

    profile_bundle.profile_provider:
        class: '%profile_bundle.profile_provider.classname%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%mmc_profile.profile_class%'

    profile_bundle.userProfile_provider:
        class: '%profile_bundle.userProfile_provider.classname%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%mmc_profile.userProfile_class%'
            - '%mmc_profile.user_class%'
            - '%mmc_profile.profile_class%'

    profile_bundle.user_browser:
        class: '%profile_bundle.user_browser.classname%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%mmc_profile.user_class%'

    profile_bundle.securizing_user_browser:
        class: '%profile_bundle.securizing_user_browser.classname%'
        arguments:
            - '@profile_bundle.user_browser'
            - '@security.authorization_checker'

    profile_bundle.user_profile_browser:
        class: '%profile_bundle.user_profile_browser.classname%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%mmc_profile.userProfile_class%'

    profile_bundle.securizing_user_profile_browser:
        class: '%profile_bundle.securizing_user_profile_browser.classname%'
        arguments:
            - '@profile_bundle.user_profile_browser'
            - '@security.authorization_checker'

    profile_bundle.user_profile_viewer:
        class: '%profile_bundle.user_profile_viewer.classname%'
        arguments:
            - '@templating'

    profile_bundle.securizing_user_profile_viewer:
        class: '%profile_bundle.securizing_user_profile_viewer.classname%'
        arguments:
            - '@profile_bundle.user_profile_viewer'
            - '@security.authorization_checker'

    profile_bundle.profile_param_converter:
        class: '%profile_bundle.profile_param_converter.classname%'
        arguments:
            - '%mmc_profile.profile_class%'
            - '@profile_bundle.profile_provider'
        tags:
            - { name: request.param_converter, priority: 2, converter: profile_param_converter }

    profile_bundle.user_param_converter:
        class: '%profile_bundle.user_param_converter.classname%'
        arguments:
            - '%mmc_profile.user_class%'
            - '@profile_bundle.user_provider'
        tags:
            - { name: request.param_converter, priority: 2, converter: user_param_converter }

    profile_bundle.user_profile_param_converter:
        class: '%profile_bundle.user_profile_param_converter.classname%'
        arguments:
            - '%mmc_profile.userProfile_class%'
            - '@profile_bundle.userProfile_provider'
        tags:
            - { name: request.param_converter, priority: 2, converter: user_profile_param_converter }

# CONTROLLERS

    profile_bundle.profile_create_controller:
        class: '%profile_bundle.profile_create_controller.classname%'
        arguments:
            - '@templating'
            - '@security.token_storage'
            - '@form.factory'
            - '@router'
            - '@profile_bundle.handler_profile_create'
            - '%mmc_profile.profile_class%'

    profile_bundle.profile_show_controller:
        class: '%profile_bundle.profile_show_controller.classname%'
        arguments:
            - '@security.token_storage'
            - '@profile_bundle.securizing_user_profile_viewer'

    profile_bundle.profile_dissociate_controller:
        class: '%profile_bundle.profile_dissociate_controller.classname%'
        arguments:
            - '@templating'
            - '@profile_bundle.user_profile.securizing_manipulator'
            - '@profile_bundle.user_profile.manager'
            - '@profile_bundle.user.manager'
            - '@router'

    profile_bundle.profile_set_priority_controller:
        class: '%profile_bundle.profile_set_priority_controller.classname%'
        arguments:
            - '@templating'
            - '@profile_bundle.user_profile.securizing_manipulator'
            - '@profile_bundle.user_profile.manager'
            - '@form.factory'
            - '@router'

    profile_bundle.profile_activate_controller:
        class: '%profile_bundle.profile_activate_controller.classname%'
        arguments:
            - '@profile_bundle.user_profile.securizing_manipulator'
            - '@profile_bundle.user_profile.manager'
            - '@router'

    profile_bundle.profile_associate_controller:
        class: '%profile_bundle.profile_associate_controller.classname%'
        arguments:
            - '@templating'
            - '@profile_bundle.user_profile.securizing_manipulator'
            - '@profile_bundle.user_profile.manager'
            - '@profile_bundle.user.manager'
            - '@router'
            - '@form.factory'
            - '@profile_bundle.user_provider'

    profile_bundle.profile_set_rights_controller:
        class: '%profile_bundle.profile_set_rights_controller.classname%'
        arguments:
            - '@templating'
            - '@profile_bundle.user_profile.securizing_manipulator'
            - '@profile_bundle.user_profile.manager'
            - '@profile_bundle.user.manager'
            - '@router'

    profile_bundle.default_controller:
        class: '%profile_bundle.default_controller.classname%'
        arguments:
            - '@templating'
            - '@security.token_storage'
            - '@profile_bundle.user.manager'

    profile_bundle.api_user_browser_controller:
        class: '%profile_bundle.api_user_browser_controller.classname%'
        arguments:
            - '@profile_bundle.securizing_user_browser'
            - '@serializer'

    profile_bundle.api_user_profile_browser_controller:
        class: '%profile_bundle.api_user_profile_browser_controller.classname%'
        arguments:
            - '@profile_bundle.securizing_user_profile_browser'
            - '@serializer'
            - '@security.authorization_checker'

# VOTERS

    profile_bundle.security.voter.user_profile:
        class: '%profile_bundle.security.voter.user_profile.classname%'
        tags:
            - { name: security.voter }

    profile_bundle.security.voter.profile:
        class: '%profile_bundle.security.voter.profile.classname%'
        tags:
            - { name: security.voter }

    profile_bundle.security.voter.user:
        class: '%profile_bundle.security.voter.user.classname%'
        tags:
            - { name: security.voter }
